openapi: 3.0.0
info:
  title: Audit API
  description: This API provides audit info
  contact:
    email: hzhou51@my.bcit.ca
  version: 1.0.0
paths:
  /stats:
    get: 
      tags:
        - stats
      summary: Return statistics about watch and scale events.
      operationId: app.get_stats
      description: Return statistics about events
      responses:
        '200':
          description: Successfully returned stats
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Stats'
  /scale:
    get: 
      tags:
        - query
      summary: get a scale reading from history
      operationId: app.get_scale
      description: gets scaling readings from event store
      parameters:
        - name: index
          in: query
          description: Gets the scale at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned scale reading
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Scale'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /watch:
      get: 
        tags:
          - query
        summary: get a scale reading from history
        operationId: app.get_watch
        description: gets watch readings from event store
        parameters:
          - name: index
            in: query
            description: Index of the desired event
            schema:
              type: integer
              example: 100
        responses:
          '200':
            description: Successfully returned watch events
            content:
              application/json:
                schema:
                  type: object
                  items:
                    $ref: '#/components/schemas/Watch'
          '400':
            description: Invalid request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string

components:
  schemas:
    Watch:
      type: object
      required:
        - device_id
        - user_id
        - exercise_type
        - distance
        - duration
        - avg_heart_rate
        - timestamp
      properties:
        device_id:
          type: string
          description: The watch ID for reporting exercise logs
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        user_id:
          type: string
          description: user's name
          example: Harry
        exercise_type:
          type: string
          example: Swimming
        distance:
          type: number
          description: distance traveled during exercise
          example: 120
          minimum: 0
        duration:
          type: number
          example: '60.0'
          minimum: 0
        avg_heart_rate:
          type: number
          minimum: 0
        timestamp:
          type: string
          description: timestamp when exercise was logged
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        trace_id:
          type: integer
          minimum: 0
    Scale:
      type: object
      required:
        - scale_id
        - weight
        - age
        - gender
        - body_fat_percentage
        - height
        - timestamp
      properties:
        scale_id:
          type: string
          description: Scale ID for the report
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        weight:
          type: number
          description: user's measured weight
          example: 72.5
          minimum: 0
        age:
          type: integer
          example: 10
        gender:
          type: string
          example: Male
        body_fat_percentage:
          type: number
          example: 15.7
          minimum: 0
        height:
          type: number
          example: 170
          minimum: 0
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        trace_id:
          type: integer
    Stats:
      required:
        - num_w
        - num_s
      properties:
        num_w:
          type: integer
          example: 100
        num_s:
          type: integer
          example: 100