version: 1
datastore:
  filename: ./data/data.json
scheduler:
  interval: 5
scalestats:
  url: http://microservices-acit3855-harry.westus2.cloudapp.azure.com/storage/fitscale/scale
watchstats:
  url: http://microservices-acit3855-harry.westus2.cloudapp.azure.com/storage/fitscale/watch
