version: 1
datastore:
  filename: ./data/data.json
scheduler:
  interval: 5
scalestats:
  url: http://storage:8090/storage/fitscale/scale
watchstats:
  url: http://storage:8090/storage/fitscale/watch
