openapi: 3.0.0
info:
  title: FitScale API
  description: Simple API for smart watches and smart scales.
  contact:
    email: hzhou51@my.bcit.ca
  version: 1.0.0
paths:
  /fitscale/watch:
    get: 
      tags:
        - watches
      summary: Watch stats from exercise events.
      operationId: app.get_watch_readings
      description: Gets exercise event stats added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of readings returned
          schema:
            type: string
            format: date-time
            example: '2025-02-13T12:11:59.000Z'
        - name: end_timestamp
          in: query
          description: Limits the number of readings returned
          schema:
            type: string
            format: date-time
            example: '2025-02-13T12:11:59.000Z'
      responses:
        '200':
          description: Successfully returned watch events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Watch'
  /fitscale/scale:
    get: 
      tags:
        - scales
      summary: Scale event statistics
      operationId: app.get_scale_readings
      description: Gets scale event stats added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of readings returned
          schema:
            type: string
            format: date-time
            example: '2025-02-13T12:11:59.000Z'
        - name: end_timestamp
          in: query
          description: Limits the number of readings returned
          schema:
            type: string
            format: date-time
            example: '2025-02-13T12:11:59.000Z'
      responses:
        '200':
          description: Successfully returned scale events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Scale'
    /count:
        get: 
          tags:
            - devices
          summary: Count of watch and scale records
          operationId: app.get_count
          description: Gets total watch and scale events
          responses:
            '200':
              description: Successfully returned count
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      watch_count:
                        type: integer
                        example: 5
                      scale_count:
                        type: integer
                        example: 100
    /watchlist:
        get: 
          tags:
            - devices
          summary: List of watch devices
          operationId: app.get_watch_list
          description: Gets list of all watch event's event ID and traice ID
          responses:
            '200':
              description: Successfully returned watch events
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      watch_list:
                        type: array
                        items:
                          type: object
                          properties:
                            event_id:
                              type: integer
                            trace_id:
                              type: string
    /scalelist:
        get: 
          tags:
            - devices
          summary: List of scale devices
          operationId: app.get_scale_list
          description: Gets list of all scale event's event ID and traice ID
          responses:
            '200':
              description: Successfully returned scale events
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      scale_list:
                        type: array
                        items:
                          type: object
                          properties:
                            event_id:
                              type: integer
                            trace_id:
                              type: string
components:
  schemas:
    Watch:
      type: object
      x-examples: {}
      required:
        - device_id
        - user_id
        - exercise_type
        - distance
        - duration
        - avg_heart_rate
        - timestamp
      properties:
        device_id:
          type: string
          description: The watch ID for reporting exercise logs
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        user_id:
          type: string
          description: user's name
          example: Harry
        exercise_type:
          type: string
          x-stoplight:
            id: 5gptu1jhyxt2r
          example: Swimming
        distance:
          type: number
          description: distance traveled during exercise
          example: 120
          minimum: 0
        duration:
          type: number
          example: '60.0'
          minimum: 0
        avg_heart_rate:
          type: number
          minimum: 0
        timestamp:
          type: string
          description: timestamp when exercise was logged
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        trace_id:
          type: integer
          minimum: 0
    Scale:
      type: object
      required:
        - scale_id
        - weight
        - age
        - gender
        - body_fat_percentage
        - height
        - timestamp
      properties:
        scale_id:
          type: string
          description: Scale ID for the report
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        weight:
          type: number
          description: user's measured weight
          example: 72.5
          minimum: 0
        age:
          type: integer
          example: 10
        gender:
          type: string
          example: Male
        body_fat_percentage:
          type: number
          example: 15.7
          minimum: 0
        height:
          type: number
          example: 170
          minimum: 0
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        trace_id:
          type: integer
