version: 1
datastore:
  kaf_hostname: kafka
  kaf_port: 29092
  topic: events
  vm_hostname: microservices-acit3855-harry.westus2.cloudapp.azure.com
  ana_hostname: analyzer
  proc_hostname: processing
  store_hostname: storage
  data_path: ./data/check.json