version: 1
datastore:
  kaf_hostname: kafka
  kaf_port: 29092
  topic: events
  ana_hostname: analyzer
  ana_port: 8110
  proc_hostname: processing
  proc_port: 8100
  store_hostname: storage
  store_port: 8090
  data_path: ./data/check.json